# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Samuel Lijin
email: sxlijin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the personal website of Samuel Lijin.
baseurl: "" # the subpath of your site, e.g. /blog
repository: sxlijin/sxlijin.github.io
github:
  url: ""

# Build settings
markdown: kramdown

permalink: pretty

exclude: [ "_dev/" ]
keep_files: [ "android-chrome-192x192.png", "android-chrome-512x512.png",
              "apple-touch-icon.png", "mstile-70x70.png", "mstile-144x144.png",
              "mstile-150x150.png", "mstile-310x150.png", "mstile-310x310.png",
              "favicon.ico", "favicon-16x16.png", "favicon-32x32.png",
              "safari-pinned-tab.svg" ]
