name: build and deploy sxlijin.github.io
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build the site
        run: |
          set -euxo pipefail

          curl -L https://github.com/jgm/pandoc/releases/download/3.1.9/pandoc-3.1.9-linux-amd64.tar.gz -o pandoc.tar.gz
          tar xf pandoc.tar.gz
          export PANDOC_CLI="$(pwd)/pandoc-3.1.9/bin/pandoc"

          curl -L https://github.com/sass/dart-sass/releases/download/1.69.5/dart-sass-1.69.5-linux-x64.tar.gz -o dart-sass.tar.gz
          tar xf dart-sass.tar.gz
          export SASS_CLI="$(pwd)/dart-sass/sass"

          ./build.sh

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v3
