name: build and deploy sxlijin.github.io
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # id-token: write is needed by actions/deploy-pages
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - run: git lfs checkout

      - name: Build the site
        run: cargo run -- build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4
